### ISSUE TITLE
Added assertions not available to subtests

### ISSUE THREAD

**Issue by medmunds** [atabel/extend-tape#2]
It looks like addAssertions only augments the top-level test function, so the added assertions are undefined in tape [subtests](https://github.com/substack/tape#ttestname-cb):

``` javascript
test('5 is bigger than 4', (t) => {
    t.biggerThan(4, 5);
    t.test('even in a subtest', (st) => {
        st.biggerThan(4, 5); // TypeError: st.biggerThan is not a function
        st.end();
    });
    t.end();
});
```

Maybe addAssertions should also patch t.test to point back to itself? Or...? (Guessing subtests aren't used very much, so may not matter.)

**Comment by atabel** [comment]
Fixed in db43588dabe3fb9755f37b1e77ccee3b0b60bfa4
:wink:
